---
layout: cv
title: Mariana Santolaja's CV
---
# Mariana Santolaja
Hi, I'm Mariana and it's nice to meet you!  I'm currently a student persuing a major in Business Analytics and a minor in Marketing. I'm passionated about data, I believe in Doctor's W. Edwards Deming saying “In God we trust. All others must bring data.” Data driven decisions are 

<div id="webaddress">
| <a href="https://www.linkedin.com/in/mariana-santolaja-62986714a/">My LinkedIn profile</a>
</div>


## Currently

Completing B.A. in Business Analysis with a Minor in Marketing (Expected Graduation: June/2028) 
Exploring full-time opportunities in marketing, business analytics, or growth strategy

### Past Experiences

__Meta — Advertising Representative | 1 year__

Supported advertisers across Meta platforms, optimizing campaigns and improving performance through data-driven insights.

Managed client communication and provided troubleshooting for ads delivery and account issues.

__Digital Marketing Agency — Marketing Assistant | 1 year__

Assisted in building and executing multi-platform digital campaigns.

Coordinated content, tracked analytics, and contributed to strategy improvements

__Crowdfunding-Focused Digital Marketing Agency — Client Support Representative | 1 year__

Guided clients through campaign launches, ensuring proper setup, branding, and messaging.

Handled customer service, answered inquiries, and maintained strong client relationships.

__Chief Detective (Growth Hacking Agency) — Growth Analyst | 1.5 years__

 Executed growth strategies, A/B tests, and funnel optimizations to increase user acquisition.

 Analyzed campaign data, identified opportunities, and implemented rapid-iteration solutions.

 Collaborated closely with marketing, product, and creative teams.

### Interests

Data analytics, performance optimization, media analysis,Python side-projects and my “Cookies-and-Cream Milk Tracker,”  spreadsheet that works as a campus tool I built to find out which vending machines are more likely to have my favorite milk based on the day of the week.


## Education

`April 2024 - Currently`
__Business Analytics, Brigham Young University - Idaho__


## Awards

`2025`
CAPSIM Club 800 — Ranked among the top students globally that achieved a 800 higher score on a Business performance simulator



## Skills

Data & Analytics: Excel, Google Analytics, SQL (basic), data visualization, reporting

Marketing: Meta Ads, campaign optimization, A/B testing, SEO basics

Business: Strategic planning, market research, financial literacy, project coordination

Tools: Google Workspace, CRM tools, Python (intermediate)

### Languages

English - Fluent

Spanish - Fluent

Portuguese - Native



<!-- ### Footer

Last updated: November 2025 -->